version: "3"
services:
  survey-consumer:
    image: survey-consumer
    build:
      context: ./survey-consumer
      dockerfile: Dockerfile-python
    networks: 
      - kafka
    # For vs code debugging
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - SQL_DRIVER="{ODBC Driver 17 for SQL Server}"
      - SQL_HOST=mssql
      - SQL_DB=ScratchDB
      - SQL_USER=sa
      - SQL_PASSWORD=HelloWorld!
      - ACQ_TOPIC=dir-survey-01
    #volumes: 
    #  - ~/.ssh:/root/.ssh
networks:
  kafka:
    # Connect to already created Kafka network
    external:
      name: kafka-trajectory-builder_default